GET http://localhost:3000/movies

###

GET http://localhost:3000/movies/5ebecdd78ca3be33765f7d79

###

POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "good movie",
    "genre": "action",
    "releaseDate": 2017
}

###

DELETE http://localhost:3000/movies/5ebf0d3656ca3814ccb17ec9

###


PATCH http://localhost:3000/movies/5ebf0d3656ca3814ccb17ec9
Content-Type: application/json

{
    "title": "test 2",
    "genre": "Accept-Encoding: ",
    "releaseDate": 2018
}